name: 'Deploy ECR Stack'

on:
  workflow_dispatch:

jobs:
  deploy-ecr:
    name: 'Deploy ECR and S3 Bucket'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 'Deploy ECR CloudFormation stack'
        run: |
          aws cloudformation deploy --template-file cloudformation/ecr.yaml --stack-name todo-app-shared-resources